### ISSUE TITLE
Maven Group ID and Artifact ID need to be changed

### ISSUE THREAD

**Issue by imesh** [osuran/azure-membership-scheme#1]
Maven group id and artifact id need to be changed according to WSO2 standards:

```
  <groupId>com.osura</groupId>
  <artifactId>membershipScheme</artifactId>
```

Please refer following:
https://github.com/wso2/kubernetes-artifacts/blob/master/common/kubernetes-membership-scheme/pom.xml

**Comment by osuran** [comment]
said Ids were changed accordingly

**Comment by imesh** [comment]
Still, the artifact id seems to be wrong, it would be better to spend more attention to detail when copying content from other sources:

``` xml
<artifactId>wso2-azure-artifacts</artifactId>
```

In WSO2 kubernetes membership scheme pom.xml file artifact id wso2-kubernetes-artifacts has been used to refer its parent:

``` xml
    <parent>
        <groupId>org.wso2.carbon.kubernetes.artifacts</groupId>
        <artifactId>wso2-kubernetes-artifacts</artifactId>
        ...
    </parent>
```

Kubernetes membership scheme artifact id is set as follows:

``` xml
 <artifactId>kubernetes-membership-scheme</artifactId>
```

**Comment by osuran** [comment]
Changed group and artifact IDs
