### ISSUE TITLE
Project does not build

### ISSUE THREAD

**Issue by imesh** [osuran/azure-membership-scheme#4]
The following build error occurs on a fresh maven local repository (~/.m2/):

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:49 min
[INFO] Finished at: 2016-08-10T11:00:13+05:30
[INFO] Final Memory: 11M/491M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project wso2-azure-artifacts: Could not resolve dependencies for project org.wso2.carbon.azure.artifacts:wso2-azure-artifacts:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: org.json.wso2:json:jar:3.0.0.wso2v1, org.wso2.carbon:org.wso2.carbon.core:jar:4.4.5, org.wso2.carbon:org.wso2.carbon.utils:jar:4.4.5: Could not find artifact org.json.wso2:json:jar:3.0.0.wso2v1 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

**Comment by isurulucky** [comment]
Please refer kubernetes or mesos membership schemes pom.xml. The issue here is the unavailability of the repositories and pluginRepositories sections.

**Comment by osuran** [comment]
Fixed the issue. It should build now
