### ISSUE TITLE
Use tags to filter VM instances belongs to a WSO2 cluster

### ISSUE THREAD

**Issue by imesh** [osuran/azure-membership-scheme#6]
Currently, it's only resource group and network security group have been used for filtering VM instances that belong to a WSO2 product cluster. In a real deployment we may need to reuse resource group and network security group for managing multiple WSO2 product clusters. 

Therefore it would be better to use tags in addition to the above parameters:

``` xml
<clustering class="org.wso2.carbon.core.clustering.hazelcast.HazelcastClusteringAgent" enable="true">
   ...
  <parameter name="resourceGroup">WSO2SecurityGroup</parameter>
  <parameter name="networkSecurityGroup">WSO2NetworkSecurityGroup</parameter>
  <!-- Define tags as a comma separated list -->
  <parameter name="tags">WSO2ESBCluster</parameter>
   ...
</clustering>
```

**Comment by isurulucky** [comment]
One possible way _might_ be to pass tags as filters to your API call [1].

[1]. http://stackoverflow.com/questions/34270735/azure-rest-api-query-parameters-for-getting-all-the-virtual-machine

**Comment by osuran** [comment]
added grouping by tags

thanks

**Comment by imesh** [comment]
Great work Osura! What would be the reason for using network interface tags? Was that the only possible way of adding tags to VMs? Thanks!

**Comment by osuran** [comment]
You can add a tag to any resource. Resources being VMs, network interfaces of VMs, network security groups, load balancers and anything in your resource group. IMO assigning a tag to the relevant network interfaces is the easiest way to group the network interfaces. After all it is the IP addresses that we are interested in. We could have assigned a tag to relevant VMs and then got the network interface, and from that the IP address also.
